version: '3.1'

services:

  io-hyperify-mysql-server:
    restart: "unless-stopped"
    container_name: io-hyperify-mysql-server
    platform: linux/amd64
    image: "io-hyperify-mysql-server:latest"
    cap_add:
    - SYS_NICE  # CAP_SYS_NICE
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_IMAGE: 'mysql:8.0.19'
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "fcRmzTX7ra9cIwGBfWn914GNjS7FmMpt"
      MYSQL_DATABASE: "hg"
      MYSQL_USER: "hg"
      MYSQL_PASSWORD: "rxPe4XHbonLeHwjvKdq9R9aDWf1xiUje"
    volumes:
    - "./volumes/mysql-data:/var/lib/mysql"
